### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by willsaid**
Finished all of the fixes necessary for version 2. Dr Evans has already approved this version for the App Store. Please review and see if you catch anything before release.

Please see the attached word doc for all of the fixes Evans has instructed me to resolve.
[ph-fixes-2.0.docx](https://github.com/calda/Brainy-Phonics/files/2228990/ph-fixes-2.0.docx)

Update:
I have amended the visual changes you specified in the last PR comment, but you may still want the Letters View Controller words to be spaced differently.

### CODE REVIEW

**Comment by calda** [comment]
All of these changes seem reasonable, looking good!

I'm seeing a few issues issues, though:
- On `QuizViewController`, the answer choices jump a few pixels when you tap on one of them:

glitch

- On `PuzzleDetailViewController`, the new bank button appears and disappears suddenly during the transition. It should fade with the same duration as the transition itself. It should also move down to the bottom of the screen when the puzzle goes full screen, rather than floating aimlessly.

glitch 2

- The splash image on `LaunchScreen.storyboard` is slightly out of place, so it jumps a few pixels when the app loads and fades to `LaunchViewController`.

glitch 3

- I think the title on `SightWordsQuizViewController` should be bold, like the letters in `LettersViewController`.

- On `LetterViewController` in Phonics mode, the cell content is off-center:

screen shot 2018-07-29 at 12 01 14 am

This one is a bit disguised, because the *views* are technically centered just fine. But take a look at the actual content alignment (red lines):

off center

On the left, you can see that currently there is more whitespace one side than the other, making the content appear off-center. This is because the art asset / content doesn't fill the entire image view (green box). 

The solution is to crop the image assets so that the `UIImage` itself doesn't have any whitespace on the left or right (example on the right). You may be able to do this algorithmically at runtime, but I suspect it would be easier to hand-crop them. That's what I did for the Alphabet Letters cell icons.

**Comment by calda** [comment]
The updated `LettersViewController` and `LaunchScreen.storyboard` look great!

- Regarding `PuzzleDetailViewController` ‒  put the Repeat button above the Bank / piggybank button, instead of moving the piggybank button when the Repeat button needs to appear. It's generally a bad idea to move buttons around on-screen.

- I'm also still seeing this issue:

43363642-49b3e190-92be-11e8-80da-9f0f185c7776

Other than those two issues, it looks good.

**Comment by willsaid** [comment]
Just swapped the bank and repeat buttons in the Puzzle Detail VC, and fixed the words superview from "jumping" up.

**Review by calda — APPROVED** [review]
Looking great!! 👍 

Ship it 🚢 🌊

**Pull request merged**
